default_stages: [ "commit", "commit-msg", "push" ]
default_language_version:
  python: python3


repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        name: "Code formatter"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        name: "End of file fixer"
      - id: debug-statements
        name: "Debug imports and breakpoints checker"
      - id: requirements-txt-fixer
        name: "Requirements txt fixer"
      - id: mixed-line-ending
        name: "Mixed line ending fixer"
      - id: check-yaml
        name: "Yaml checker"
        args: [ '--unsafe' ]
      - id: trailing-whitespace
        name: "Trailing whitespace fixer"

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: "Linter"
        additional_dependencies:
          - pep8-naming
          - flake8-builtins
          - flake8-comprehensions
          - flake8-bugbear
          - flake8-pytest-style
          - flake8-cognitive-complexity
          - flake8-pyproject
          - importlib-metadata<5.0

  - repo: local
    hooks:
      - id: mypy
        name: "Static type checker"
        entry: python -m mypy mava/
        language: system
        types: [ python ]
        pass_filenames: false

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.11.0
    hooks:
      - id: commitlint
        name: "Commit linter"
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: insert-license
        name: "License inserter"
        files: .*py$
        args:
          - --license-filepath=docs/license_header.txt
          - --comment-style=#
        exclude: .npy$  # Do not add license to .npy files (the standard binary file format in NumPy)
